kafka:
  bootstrap_servers: "kafka-server:9092"
  topic: "events-topic"

producer:
  start_id: 1
  increment: 1
  message: "Hello World"
  sleep_time: 1
  metricValue_min: 1
  metricValue_max: 100
  metricId_min: 1
  metricId_max: 10

