kafka:
  bootstrap_servers: "kafka-server:9092"
  topic: "events-topic"
  group_id: "event-consumers-group"
  offset_reset: "earliest"

mongo:
  uri: "mongodb://mongo:27017"
  database: "kafka-events"
  collection: "EVENTS"

consumer:
  poll_timeout: 1.0
