services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - kafka-compose_kafka-network

networks:
  kafka-compose_kafka-network:
    external: true