services:
  redis-server:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - kafka-compose_kafka-network

networks:
  kafka-compose_kafka-network:
    external: true