mongo:
  uri: "mongodb://mongo:27017"
  database: "kafka-events"
  collection: "EVENTS"

redis:
  host: "redis-server"
  port: 6379
  last_timestamp_key: "last_timestamp"

etl:
  max_entries: 5000
  max_entries_gt: 3000
  sleep_time: 30
  event_count: 0
  event_count_incr: 1